version: "3"

services:
  redis:
    image: redis:7
    # no public port (internal only)
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - pgdata:/var/lib/postgresql/data
    # no public port (internal only)
    restart: unless-stopped

  vote:
    image: ${ECR_REGISTRY}/vote:${IMAGE_TAG:-latest}
    ports:
      - "5000:80"
    depends_on:
      - redis
      - db
    restart: unless-stopped

  worker:
    image: ${ECR_REGISTRY}/worker:${IMAGE_TAG:-latest}
    depends_on:
      - redis
      - db
    restart: unless-stopped

  result:
    image: ${ECR_REGISTRY}/result:${IMAGE_TAG:-latest}
    ports:
      - "5001:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
