services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  vote:
    build:
      context: ../../../vote
    ports: ["5000:80"]
    depends_on: [redis]

  worker:
    build:
      context: ../../../worker
    depends_on: [redis, db]

  result:
    build:
      context: ../../../result
    ports: ["5001:80"]
    depends_on: [db]

volumes:
  pgdata:
