apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting
spec:
  selector:
    app: vote
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: vote
          image: __ECR__/vote:__TAG__
          ports:
            - containerPort: 80
              hostPort: 5000      # expose to the EC2 like before
          env:
            - name: REDIS
              value: redis
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: db, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: db, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: db, key: POSTGRES_DB } }
