apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: worker
          image: __ECR__/worker:__TAG__
          env:
            - name: REDIS
              value: redis
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: db, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: db, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: db, key: POSTGRES_DB } }
